name: pipeline
dependencies:
- git=2.6.4=0
- pip=8.1.1=py27_1
- python=2.7.11=4
- setuptools=20.7.0=py27_0
- vs2008_runtime=9.00.30729.1=0
- wheel=0.29.0=py27_0
- pip:
  - "--editable=git+https://github.com/pyblish/pyblish-rpc.git#egg=pyblish-rpc"
  - "--editable=git+https://github.com/pyblish/pyblish-qml.git#egg=pyblish-qml"
  - "--editable=git+https://github.com/pyblish/pyblish-base.git#egg=pyblish-base"
# installing pyqt5 not in developer mode, sets the qt.conf up correctly
  - "git+https://github.com/pyqt/python-qt5.git"
